import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 60,
    paddingHorizontal: 10,
    paddingBottom: 20,
  },
  title: {
    fontSize: 30,
    marginTop: -10,
    fontWeight: 'bold',
    color: '#ffffff',
    marginInlineEnd: 20,
  },
  agendaButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(13, 233, 241, 1)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    marginTop: -30,
  },
  agendaButtonText: {
    color: '#ffffff',
    marginLeft: 5,
    fontWeight: '600',
  },
  agendaButtonText1: {
    color: '#ffffff',
    marginLeft: 5,
    fontWeight: '600',
  },
    backButton: {
    position: 'absolute',
    top: 555,
    left: 50,
    zIndex: 10,
  },
  searchContainer: {
    paddingHorizontal: 20,
    paddingBottom: 15,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(14, 244, 6, 0.89)',
    borderRadius: 20,
    paddingHorizontal: 15,
    height: 50,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchPlaceholder: {
    flex: 1,
    color: '#aaaaaa',
    fontSize: 16,
  },
  filterContainer: {
    marginBottom: 40,
    maxHeight: 50,
    paddingBottom: 10,
  },
  filterButton: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingVertical: 8,
  paddingHorizontal: 15,
  borderRadius: 10,
  marginRight: 10,
  borderWidth: 2,
  borderColor: 'transparent',
  transform: [{ translateY: 0 }], // Estado normal
},
  filterButtonActive: {
  borderWidth: 2,
  borderColor: '#ffffffff',
  transform: [{ translateY: 8 }], // ✅ "Baja" el botón 3px
},
  filterText: {
    marginLeft: 5,
    color: '#f9f3f3ff',
    fontSize: 14,
    fontWeight: '600',
  },
  calendarContainer: {
    backgroundColor: 'rgba(15, 14, 14, 0.22)',
    marginTop: -10,
    borderRadius: 15,
    marginHorizontal: 20,
    marginBottom: 20,
    overflow: 'hidden',
  },
  addButton: {
    flexDirection: 'row-reverse',
    backgroundColor: 'rgba(77, 251, 2, 1)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    position: 'absolute',
    top: 555,
    right: 36,
    bottom: 30,
    width: 150,
    height: 45,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 'auto',
  },
  modalContainer: {
    width: 'auto',
    height: 'auto',
    backgroundColor: '#210af4fb',
    borderRadius: 12,
    maxHeight: '90%',
    paddingVertical: 'auto',
    overflow: 'hidden',
  },
  // modalOverlay: {
  //   flex: 1,
  //   backgroundColor: 'rgba(0, 0, 0, 0.7)',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // modalContainer: {
  //   width: '90%',
  //   maxHeight: '80%',    // ← Altura máxima controlada
  //   backgroundColor: '#210af4fb',
  //   borderRadius: 12,
  //   overflow: 'hidden',
  //   // ❌ SIN flex: 1 aquí
  // },
  modalContent: {
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  closeButton: {
    padding: 5,
  },
  inputGroup: {
    marginBottom: 8,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 8,
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    padding: 15,
    color: '#ffffff',
    fontSize: 16,
    marginBottom: 5,
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  typeSelector: {
    flexDirection: 'row',
    marginVertical: 1,
    marginBottom: -5,
  },
  typeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 2,
    marginBottom: 20,
    // Estilo base con elevación/sombra
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  typeOptionSelected: {
    transform: [{ translateY: 20 }],
    elevation: 1,
    shadowOffset: { width: 0, height: 0.5 },
  },
  typeOptionText: {
    marginLeft: 4,
    fontSize: 14,
    fontWeight: '600',
  },
  timeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    padding: 15,
  },
  timeButtonText: {
    marginLeft: 10,
    color: '#ffffff',
    fontSize: 16,
  },
  modalFooter: {
    marginTop: 20,
    alignItems: 'center',
  },
  saveButton: {
    backgroundColor: '#76fd09ff',
    borderRadius: 8,
    padding: 15,
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  // Agregar estos estilos al archivo existente
  statsContainer: {
  flexDirection: 'row',
  justifyContent: 'center',
  marginBottom: 10,
  gap: 15,
},
  statsText: {
  color: 'white',
  fontSize: 12,
  fontWeight: '600',
  backgroundColor: 'rgba(255,255,255,0.2)',
  paddingHorizontal: 8,
  paddingVertical: 4,
  borderRadius: 10,
},
  quickActionsContainer: {
  flexDirection: 'row',
  justifyContent: 'center',
  marginBottom: 15,
  gap: 10,
},
  quickActionButton: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: 'rgba(255,255,255,0.1)',
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderRadius: 20,
  borderWidth: 1,
  borderColor: 'rgba(255,255,255,0.3)',
},
  quickActionText: {
  color: 'white',
  fontSize: 12,
  marginLeft: 5,
},
  todayContainer: {
  backgroundColor: 'rgba(255,255,255,0.1)',
  padding: 15,
  borderRadius: 15,
  marginHorizontal: 15,
  marginBottom: 15,
  borderWidth: 1,
  borderColor: 'rgba(255,255,255,0.2)',
},
  todayTitle: {
  color: 'white',
  fontSize: 16,
  fontWeight: 'bold',
  marginBottom: 10,
},
  todayAppointment: {
  backgroundColor: 'rgba(255,255,255,0.9)',
  padding: 12,
  borderRadius: 10,
  marginRight: 10,
  minWidth: 150,
  borderLeftWidth: 4,
},
  todayAppointmentText: {
  fontSize: 14,
  fontWeight: 'bold',
  color: '#333',
},
  todayAppointmentTime: {
  fontSize: 12,
  color: '#666',
  marginTop: 4,
},
  completeButton: {
  position: 'absolute',
  top: 5,
  right: 5,
  backgroundColor: 'rgba(0,255,0,0.2)',
  borderRadius: 12,
  padding: 4,
},
});

export default styles;